Repository prisma/docs, pull requests merged in 2021-08, with the labels that each got.

#2132 fix(error-reference): Add structure
  content/400-reference/200-api-reference/250-error-reference.mdx
Labels: docs

#1908 fix(connection-management): Clarify beforeExit hook
  content/200-concepts/100-components/02-prisma-client/000-working-with-prismaclient/100-connection-management.mdx
Labels: docs

#2126 feat: Split "About" in "Prisma" and "Prisma Docs"
  content/600-about/100-prisma/10-releases.mdx
  content/600-about/100-prisma/20-example-projects.mdx
  content/600-about/100-prisma/30-roadmap.mdx
  content/600-about/100-prisma/40-faq.mdx
  content/600-about/100-prisma/50-limitations.mdx
  content/600-about/100-prisma/index.mdx
  content/600-about/200-prisma-docs/00-whats-new-in-prisma-docs.mdx
  content/600-about/200-prisma-docs/10-about-the-docs.mdx
  content/600-about/200-prisma-docs/20-style-guide/01-mdx-examples.mdx
  content/600-about/200-prisma-docs/20-style-guide/02-template.mdx
  content/600-about/200-prisma-docs/20-style-guide/03-frontmatter.mdx
  content/600-about/200-prisma-docs/20-style-guide/index.mdx
  content/600-about/200-prisma-docs/index.mdx
  content/600-about/index.mdx
Labels: docs

#2029 Relations troubleshooting: m-n self-relation
  content/200-concepts/100-components/01-prisma-schema/06-relations/500-troubleshooting-relations.mdx
Labels: docs

#1943 fix: Do not convert query part of URLs to lowercase
  plugins/gatsby-remark-check-links-numberless/index.js
  plugins/gatsby-remark-to-absoluteurl/index.js
Labels: website

#1567 fix: Schema / Generators
  content/200-concepts/100-components/01-prisma-schema/03-generators.mdx
Labels: docs

#1667 fix(Introspection): Small fixes and changes
  content/200-concepts/100-components/04-introspection.mdx
Labels: docs

#2155 Remove mention of TLS workaround
  content/200-concepts/100-components/250-preview-features/100-sql-server/001-sql-server-start-from-scratch.mdx
Labels: topic: sql server

#1929 fix(prisma-client-reference): De-emphathize beforeExit and improve $on documentation
  content/400-reference/200-api-reference/050-prisma-client-reference.mdx
Labels: docs
