Repository prisma/docs, pull requests merged in 2022-04, with the labels that each got.

#3013 Add type mappings to Mongo connector docs
  content/200-concepts/200-database-connectors/07-mongodb.mdx
Labels: topic: mongodb

#2787 Add `--transpile-only` flag to seed script
  content/300-guides/050-database/300-seed-database.mdx
Labels: docs, docs/candidate, docs/improvement, technical review

#3068 fix(command-reference): remove MongoDB Preview mentions
  content/400-reference/200-api-reference/200-command-reference.mdx
Labels: topic: mongodb

#2926 Update Navbar.tsx
  src/components/navbar/Navbar.tsx
Labels: web/candidate, website

#2692 fix(sidebar): stop the confusion between cli and client (#2691)
  src/components/sidebar/treeNode.tsx
Labels: website

#3063 Guide to generating down migrations
  content/300-guides/050-database/100-developing-with-prisma-migrate/180-generating-down-migrations.mdx
Labels: docs
