Repository prisma/docs, pull requests merged in 2022-02, with the labels that each got.

#2840 fix: stop lowercase of urls
  content/300-guides/050-database/850-using-prisma-with-planetscale.mdx
  content/300-guides/125-development-environment/100-editor-setup.mdx
  content/300-guides/200-deployment/110-deployment-guides/400-deploying-to-aws-lambda.mdx
  content/300-guides/200-deployment/110-deployment-guides/650-caveats-when-deploying-to-aws-platforms.mdx
  content/400-reference/200-api-reference/050-prisma-client-reference.mdx
  content/400-reference/200-api-reference/100-prisma-schema-reference.mdx
  plugins/gatsby-remark-check-links-numberless/index.js
  plugins/gatsby-remark-to-absoluteurl/index.js
Labels: website/bug, website

#1569 ci: GH Actions workflow that outputs a list of the changed docs URLs
  .github/workflows/list-changed-pages.yml
Labels: website

#2873 fix(data-model): Remove irrelevant sentence
  content/200-concepts/100-components/01-prisma-schema/04-data-model.mdx
Labels: topic: mongodb

#2881 fix(crud): @@id is an attribute, remove wrong sentence
  content/200-concepts/100-components/02-prisma-client/030-crud.mdx
Labels: topic: mongodb

#2886 fix(command-reference): `db push` is supported for MongoDB
  content/400-reference/200-api-reference/200-command-reference.mdx
Labels: topic: mongodb

#2878 fix(referential-actions): Combine "types" tables into one
  content/200-concepts/100-components/01-prisma-schema/06-relations/425-referential-actions/index.mdx
Labels: topic: mongodb

#2874 fix(data-model): Optional and mandatory fields with MongoDB
  content/200-concepts/100-components/01-prisma-schema/04-data-model.mdx
Labels: topic: mongodb

#2875 fix(data-model): Rewrite MongoDB unsupported type story (all supported)
  content/200-concepts/100-components/01-prisma-schema/04-data-model.mdx
Labels: docs, topic: mongodb

#2879 fix(features-without-psl-equivalent): Turn MongoDB admonition into normal sentences
  content/200-concepts/100-components/01-prisma-schema/08-features-without-psl-equivalent.mdx
Labels: topic: mongodb

#2824 Change @db.Array(ObjectID) to @db.ObjectID
  content/200-concepts/100-components/01-prisma-schema/04-data-model.mdx
  content/200-concepts/100-components/01-prisma-schema/06-relations/300-many-to-many-relations.mdx
  content/200-concepts/100-components/01-prisma-schema/06-relations/400-self-relations.mdx
  content/200-concepts/100-components/01-prisma-schema/06-relations/index.mdx
  content/200-concepts/100-components/02-prisma-client/051-working-with-fields/200-working-with-scalar-lists-arrays.mdx
  content/400-reference/200-api-reference/100-prisma-schema-reference.mdx
Labels: topic: mongodb

#2912 MongoDB 4.2 support
  content/400-reference/300-database-reference/03-supported-databases.mdx
Labels: topic: mongodb
