Repository prisma/docs, pull requests merged in 2022-05, with the labels that each got.

#3123 PostgreSQL inverted indices
  content/200-concepts/100-components/01-prisma-schema/09-indexes.mdx
Labels: topic: extended indexes

#3128 CDB: Rename SingleChar native type to CatalogSingleChar
  content/400-reference/200-api-reference/100-prisma-schema-reference.mdx
Labels: topic: cockroachdb

#3129 CockroachDB Sequences
  content/200-concepts/200-database-connectors/08-cockroachdb.mdx
  content/400-reference/200-api-reference/100-prisma-schema-reference.mdx
Labels: topic: cockroachdb

#3107 Add type mapping tables to the CockroachDB connector
  content/200-concepts/200-database-connectors/08-cockroachdb.mdx
Labels: topic: cockroachdb

#3070 Add redirects from website-v8 here directly instead
  gatsby-config.js
  static/_redirects
Labels: website

#3166 Update 400-self-relations.mdx
  content/200-concepts/100-components/01-prisma-schema/06-relations/400-self-relations.mdx
Labels: technical review

#3057 guide: mongoose migration guide
  content/200-concepts/300-more/400-comparisons/03-prisma-and-mongoose.mdx
  content/300-guides/400-migrate-to-prisma/01-migrate-from-typeorm.mdx
  content/300-guides/400-migrate-to-prisma/02-migrate-from-sequelize.mdx
  content/300-guides/400-migrate-to-prisma/03-migrate-from-mongoose.mdx
Labels: docs, topic: mongodb
