Repository prisma/docs, pull requests merged in 2023-11, with the labels that each got.

#5419 Add guide for using SafeQL and extensions to help unsupported features.
  content/300-guides/500-other/900-advanced-database-tasks/06-typesafe-raw-sql/01-safeql.mdx
  content/300-guides/500-other/900-advanced-database-tasks/06-typesafe-raw-sql/index.mdx
Labels: defer

#4629 Adds section on viewing connection pool status with logging & metrics
  content/200-concepts/100-components/02-prisma-client/000-working-with-prismaclient/115-connection-pool.mdx
Labels: defer

#5273 docs: imperative vs declarative terminology for Prisma Migrate
  content/200-concepts/100-components/03-prisma-migrate/index.mdx
Labels: defer

#5272 docs: remove duplication in shared client extensions pages
  content/200-concepts/100-components/02-prisma-client/053-client-extensions/140-shared-extensions.mdx
Labels: defer, one-page-pr

#5343 Update some mentions of Data Browser
  content/600-about/200-prisma-docs/20-style-guide/05-prisma-product-names.mdx
Labels: defer

#4724 Include Prisma Client installation and client generation with `migrate dev`
  content/100-getting-started/01-quickstart.mdx
Labels: defer

#4940 fix: update note in admonition
  content/400-reference/200-api-reference/050-prisma-client-reference.mdx
Labels: defer

#3168 Reference to auth source in mongo url
  content/100-getting-started/02-setup-prisma/200-add-to-existing-project/120-mongodb/100-connect-your-database.mdx
Labels: topic: mongodb

#3115 Clarify that _null enums_ require use of `equals`
  content/200-concepts/100-components/02-prisma-client/051-working-with-fields/100-working-with-json-fields.mdx
Labels: merge-conflict, merge-conflict-serious
