Repository prisma/docs, pull requests merged in 2023-07, with the labels that each got.

#4989 make extendedWhereUnique GA
  content/200-concepts/100-components/02-prisma-client/054-middleware/100-soft-delete-middleware.mdx
  content/200-concepts/100-components/250-preview-features/050-client-preview-features.mdx
  content/300-guides/100-performance-and-optimization/100-prisma-client-transactions-guide.mdx
  content/400-reference/200-api-reference/050-prisma-client-reference.mdx
Labels: topic: prisma5

#4987 make `jsonProtocol` GA
  content/200-concepts/100-components/250-preview-features/050-client-preview-features.mdx
Labels: topic: prisma5

#5015 Update TS minimum from 4.1 to 4.7
  content/400-reference/100-system-requirements.mdx
Labels: docs, topic: prisma5

#4928 Remove Node v14 - add Node v20
  content/100-getting-started/01-quickstart.mdx
  content/300-guides/200-deployment/110-deployment-guides/150-deploying-to-azure-functions.mdx
  content/400-reference/100-system-requirements.mdx
Labels: docs, topic: prisma5

#4789 Remove docs for postgres 9.4 & 9.5 support
  content/400-reference/300-database-reference/03-supported-databases.mdx
Labels: docs, topic: prisma5

#5049 Jharrell/issue5044
  content/300-guides/300-upgrade-guides/200-upgrading-versions/600-upgrading-to-prisma-5.mdx
Labels: docs

#5063 Document how to escape SQL Server connection string parts
  content/200-concepts/200-database-connectors/08-sql-server/index.mdx
  content/400-reference/300-database-reference/02-connection-urls.mdx
Labels: docs, topic: sql server
